# Generated by Django 5.2.5 on 2025-10-26 23:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок поста (максимум 200 символів)', max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Основний текст поста', verbose_name='Вміст')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата та час створення поста', verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата та час останнього оновлення', verbose_name='Дата оновлення')),
                ('is_published', models.BooleanField(default=True, help_text='Чи опублікований пост', verbose_name='Опубліковано')),
                ('author', models.ForeignKey(help_text='Автор поста', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Пости',
                'ordering': ['-created_at'],
            },
        ),
    ]
